package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"example.com/pz12-rest-vs-graphql/graph/model"
	"example.com/pz12-rest-vs-graphql/internal/task"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	item, err := r.TaskService.Create(ctx, task.CreateInput{
		Title:       input.Title,
		Description: description,
	})
	if err != nil {
		return nil, err
	}

	return toModelTask(item), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	item, err := r.TaskService.Update(ctx, id, task.UpdateInput{
		Title:       input.Title,
		Description: input.Description,
		Done:        input.Done,
	})
	if err != nil {
		return nil, err
	}

	return toModelTask(item), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.TaskService.List(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Task, 0, len(tasks))
	for i := range tasks {
		result = append(result, toModelTask(&tasks[i]))
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	item, err := r.TaskService.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	return toModelTask(item), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
