package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"example.com/pz11-graphql/services/graphql/graph/model"
	"example.com/pz11-graphql/services/graphql/internal/service"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}

	task, err := r.TaskService.CreateTask(ctx, service.CreateTaskInput{
		Title:       input.Title,
		Description: description,
	})
	if err != nil {
		return nil, err
	}

	return toModelTask(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	task, err := r.TaskService.UpdateTask(ctx, id, service.UpdateTaskInput{
		Title:       input.Title,
		Description: input.Description,
		Done:        input.Done,
	})
	if err != nil {
		return nil, err
	}

	return toModelTask(task), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if err := r.TaskService.DeleteTask(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.TaskService.ListTasks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Task, 0, len(tasks))
	for i := range tasks {
		result = append(result, toModelTask(&tasks[i]))
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.TaskService.GetTask(ctx, id)
	if err != nil {
		return nil, err
	}

	return toModelTask(task), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
